
name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven

      - name: Build and Test orders-service
       # working-directory: BE-MS/orders-service
        run: mvn -B package --file pom.xml

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          
          name: orders-service
          path: /orders-service/target/*.jar

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
            path: ~/.sonar/cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2

      - name: Build test con sonarcloud
#        working-directory: orders-service
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=SD-MS-DevOps_orders-service

  #  orders-service

     # - name: Build and Test orders-service
       # working-directory: BE-MS/orders-service
     #   run: mvn -B package --file pom.xml

      #- name: Upload JAR file
      #  uses: actions/upload-artifact@v4
      #  with:
       #   name: orders-service
       #   path: orders-service/target/*.jar

      #- name: Download JAR file
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: orders-service
      #    path: BE-MS/orders-service/

      #- name: Build and push Docker image
       # run: docker build -t orders-service:latest ./BE-MS/orders-service
