
name: Workflow
on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:

  repository_dispatch:

    runs-on: ubuntu-latest

    steps:
      # Verificar la rama   
      - name: Repository Dispatch for develop
        if: github.ref_name == 'develop'
        uses: peter-evans/repository-dispatch@v3
        with:
           token: ${{ secrets.REPO_ACCESS_TOKEN }}
           repository: SD-MS-DevOps/IaC-DevOps
           event-type: orders-service
           client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}"}'
  
      - name: Repository Dispatch for staging
        if: github.ref_name == 'staging'
        uses: peter-evans/repository-dispatch@v3
        with:
           token: ${{ secrets.REPO_ACCESS_TOKEN }}
           repository: SD-MS-DevOps/IaC-DevOps
           event-type: orders-service
           client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}"}'
  
      - name: Repository Dispatch for main
        if: github.ref_name == 'main'
        uses: peter-evans/repository-dispatch@v3
        with:
           token: ${{ secrets.REPO_ACCESS_TOKEN }}
           repository: SD-MS-DevOps/IaC-DevOps
           event-type: orders-service
           client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}"}'    