
name: Workflow DEV
on:
  push:
    branches:
      - develop

jobs:
  
  repository_dispatch:

    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: SD-MS-DevOps/IaC-DevOps
          event-type: orders-service
          client-payload: '{"ref": "refs/heads/develop", "sha": "${{ github.sha }}"}'
      
    