name: Workflow 
on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:

  repository_dispatch:

    runs-on: ubuntu-latest

    steps:
      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8
      # Verificar la rama   
            # Detect branch type and set environment
      - name: Set environment variable
        run: |
             echo "BRANCH=${{ steps.branch-names.outputs.ref_branch }}" >> $GITHUB_ENV 
            
      - run:  echo "${{ env.BRANCH}}"
      - name: Dispatch repository event
        uses: peter-evans/repository-dispatch@v3
        with:
               token: ${{ secrets.REPO_ACCESS_TOKEN }}
               repository: SD-MS-DevOps/IaC-DevOps
               event-type: ms-service
               client-payload: '{"ref": "${{ github.ref }}","sha": "${{ github.sha }}","repository": "${{ github.repository }}"}'
              
 #,"environment": "${{ env.BRANCH }}"}'
                 